### ISSUE TITLE
No update from c64-go

### ISSUE THREAD

**Issue by Dtrieb** [ripper121/odroidgoupdater#3]
Can you help me, why I didn't get the last version from: https://github.com/Schuemi/c64-go/issues/12

**Comment by ripper121** [comment]
What's the error message?

**Comment by Dtrieb** [comment]
I didn't get an error message.
It says all up to date.

My c64-go version on the card is 20190228

**Comment by ripper121** [comment]
That means that the Author has not created a new release yet.
If he has added new features, then maybe only to the sources, ask him to create a new release (no pre-release).
